package com.example.movieapp.presentation.models.movie_info

data class MovieInfoUiModel(
    val backdropPath: String,
    val budget: Int,
    val genres: List<GenreUiModel>,
    val homepage: String,
    val id: Int,
    val imdbId: String,
    val originalLanguage: String,
    val originalTitle: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val releaseDate: String,
    val revenue: Int,
    val runtime: Int,
    val spokenLanguages: List<SpokenLanguageUiModel>,
    val status: String,
    val tagline: String,
    val title: String,
    val video: Boolean,
    val voteAverage: Double,
    val voteCount: Int,
//    val adult: Boolean,
//    val productionCompanies: List<ProductionCompanyUiModel>,
//    val productionCountries: List<ProductionCountryUiModel>,
//    val belongsToCollection: BelongsToCollectionUiModel,
)